### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by CaptainAchilles**
Changed port to be different to the dev port

### CODE REVIEW

**Review by MrCeleryman — DISMISSED** [review]
Non Constructive
Please add a reason for the change.

**Comment by CaptainAchilles** [comment]
Database server should be more different than the dev port than by one

**Comment by MrCeleryman** [comment]
Why?

**Comment by CaptainAchilles** [comment]
SO that is it less confusing when doing the port numbers

**Comment by MrCeleryman** [comment]
Are you planning on using port 8081 for the test server?

**Review by JonathanHolland — APPROVED** [review]
Approved, this shouldn't take so long Dan this is your fault

**Comment by CaptainAchilles** [comment]
It makes sense to if the tests are running in parallel to occupy all of the 808* range. It seems odd to have the dev server on 8080, the db server on 8081, and the tests onwards

**Comment by MrCeleryman** [comment]
Ok I approve

**Pull request merged**
