### PR TITLE
Improvement linting #20

### PR DESCRIPTION
**Pull request by CaptainAchilles**
Added linting to the project files.
Use `npm run lint`, or run the webpack build process to get a lint report.

The linter automatically looks at the ts component of .vue files, or all raw .ts files.

### CODE REVIEW

**Review by MrCeleryman — COMMENTED** [review]
I have added a commit to add some more eslint rules and fixed the errors arising from the rules

* comma-dangle - changed to all cases no dangle
* keyword-spacing
* linebreak-style to off because we have multiple dev OS's i saw it being too much hassle to keep it on
* quotes - double with allowing backticks to template literals
* require-jsdoc - can re implement later if wanted?
* max-len - changed to 120 and ignores comments
* guard-for-in turned off
* object-curly-spacing on because it looks nice imo

Thoughts?

Happy to approve otherwise

**Comment by CaptainAchilles** [comment]
Hey Dan, thanks for more of your great contributions!

I think we should also address the spaces vs. tabs in our source files, I noticed that some developers are using tabs for indentation, while others are using spaces. I have personally configured my dev environment to always use spaces.

Setting the line endings in git is quite trivial; just use `git config --global core.autocrlf true`.

I am also curious on the justification on 120 chars? 80 chars seems to be the computing standard, even though it is stemmed from a time where many variables were abbreviated, or single letters.

I also think we should keeo the for-in guard, even though we are using typescript. It is generally bad form not to check object properties in javascript using a for..in.

**Comment by MrCeleryman** [comment]
Happy the change from 120 to 80, personally just makes it inconvenient especially since computer screens are much bigger these days.

line endings like a non issue too unless there is one I am not seeing.

I can change the for in guard too.

As for spaces vs tabs, I started this project using tabs and intending for it to be tabs only so I will not change this unless there is a project breaking reason for not doing so. I plan to also implement the no-mixed-spaces-tabs rule to enforce this.

**Comment by CaptainAchilles** [comment]
I only brought it up because git has a hard time separating out lines when it is indented with a tab or space.
See the package.json file in [6b7b86969945e2c8b641b92e6e87e7270e72c5b4](https://github.com/MrCeleryman/Parmyay/pull/24/commits/6b7b86969945e2c8b641b92e6e87e7270e72c5b4)
I think it would be a positive change for the project to commit a workspace .vscode file as well, so that our personal settings are override by the project standards.

I'll make another ticket for the .vscode settings #25

**Comment by MrCeleryman** [comment]
The vs code setting is a good idea!

As for the package.json, json files are usually 2 spaced files so I am ok with that being spaces and not tabs

**Comment by CaptainAchilles** [comment]
Interesting about the package.json indentation: [3062](https://github.com/npm/npm/pull/3062)
I'm sure we could easily add an exception to it.

I will also update #25 to include a .gitattributes file to help maintain project uniforminity

**Comment by MrCeleryman** [comment]
Made the changes I said I would

**Review by MrCeleryman — APPROVED** [review]

**Pull request merged**
