### PR TITLE
Adding Parmy Localisation fixes #12

### LINKED ISSUE #12: Centralise Language
At the moment, the nouns used for parmy are set up in a very messy/prototype-ish way. They should be moved to a static class, which internally manages a language definition for parmy. It should be able to listen on changes and update its state (Vue listens to) through something like a global event bus.

### PR DESCRIPTION
**Pull request by CaptainAchilles**
+ Added localisation for parmy in a static class. This prevents event
bubbling to the top of the application.
+ Changed class export names to match the file names.
fixes #12

### CODE REVIEW

**Comment by MrCeleryman** [comment]
Looks good but I also have a PR up changing the routing structure, how do we go about both of them?

**Comment by CaptainAchilles** [comment]
Pulled in changes from master to prevent merge conflicts from #1.

**Review by MrCeleryman — CHANGES_REQUESTED** [review]
Getting property changeLang and LANG undefined can you please have a look to see what the problem is?

**Comment by CaptainAchilles** [comment]
Thanks for the heads up! I have removed those old LANG references and everything seems good on my end now 🎉 Could you give it another check?

**Review by MrCeleryman — APPROVED** [review]

**Comment by MrCeleryman** [comment]
Looks good now great work! These changes will make it much more stable in future 🎉

**Pull request merged**
