### PR TITLE
fixes #2 - working prototype

### LINKED ISSUE #2: Implement switch for multiple parmy nouns
At the moment we can only switch between parma and parmi. A circular switch needs to be implemented so that we can toggle between an arbitrary number of spellings

### PR DESCRIPTION
**Pull request by MrCeleryman**
Tell us what you think.
I think it can be greatly improved on but I think it is pretty solid for now

### CODE REVIEW

**Comment by CaptainAchilles** [comment]
Good start, we need to keep in mind not to keep the LANG object inside of the main Vue instance. An event bus that passes around a global 'changeLang' event would be more suitable, but there is a ticket that covers this anyway. 

I think your TriSwitch implementation is flawed, why not just have a variable storing that current state, rather than 3 option variables? It makes scaling very hard.

Why are you excluding node_modules in the tsconfig? IIRC it will block automatic @types resolution for planned things like d3.

**Comment by CaptainAchilles** [comment]
Merge approved if tickets are opened for the issues I raised; it is a step forward and the implementation can be built on more easily than the previous version.

**Review by CaptainAchilles — APPROVED** [review]

**Comment by MrCeleryman** [comment]
I agree it is a very flawed implementation but I think it is a step in the right direction and will be much easier to change than the previous implementation as stated.

As for node_modules i think you may be right as my reasoning for that is types did not used to be in node_modules in pre 2.0 typescript so I don't know if excluding node_modules will affect types now.

**Comment by JonathanHolland** [comment]
Thanks for your work Dan, make sure to also delete the merged branch in cases where you know you won't want to make patches on that feature 👍

**Pull request merged**
